apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vk-service.fullname" . }}-config
data:
  application.yml: |
    tarantool:
      host: {{ .Values.tarantool.host }}
      port: {{ .Values.tarantool.port }}
      user: {{ .Values.tarantool.user }}
    redis:
      host: {{ .Values.redis.host }}
      port: {{ .Values.redis.port }}
      ttl-seconds: {{ .Values.redis.ttlSeconds }}
