apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vk-service.fullname" . }}-secret
type: Opaque
data:
  TARANTOOL_PASSWORD: {{ .Values.tarantool.password | b64enc }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
