apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vk-service.fullname" . }}-config
data:
  TARANTOOL_HOST: {{ .Values.tarantool.host | quote }}
  TARANTOOL_PORT: {{ .Values.tarantool.port | quote }}
  TARANTOOL_USER: {{ .Values.tarantool.user | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  REDIS_TTL_SECONDS: {{ .Values.redis.ttlSeconds | quote }}
