{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vk-service.fullname" . }}
  labels:
    {{- include "vk-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vk-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 15s
      path: /actuator/prometheus
{{- end }}
